### ISSUE TITLE
Request to buff Shield Capacity of Interceptor

### ISSUE THREAD

**Issue by ghost** [AY-KE-4519/starblast-torpedo-dueling-championship#1]
Interceptor's shield capacity is 250. And torpedo's damage is 500. Straightaway this means 250 gems will be lost on torpedo hit. And 250 gems are just tooooooo much. So I think the shield capacity should be buffed, and perhaps the ship should be made tier 7. Else 1 jiffy of lag can turn the sides of the game at any moment by a lot of extent.

**Comment by Rebuk-x** [comment]
This is a dueling mod, so there is nothing to do with tiers. Also, sure, I will buff the shield capacity to 325. Hope thats okay...

**Comment by ghost** [comment]
No, it has
Tier 6=720 Gems
Tier 7=980 Gems
Replying to that "nothing to do with tiers" part of your msg

**Comment by Rebuk-x** [comment]
But dueling needs only 720 gems. Now finish off the issue

**Comment by ghost** [comment]
okay
said just bcoz torpedoes do a lot of damage
